from typing import Any

class Attr:
    infer_types: Any = ...
    PrimType: Any = ...
    __bind__: Any = ...
    @classmethod
    def create(cls: Any, name: Any, value: Any) -> Any: ...
    name: Any = ...
    def __init__(self, name: Any, value: Any) -> None: ...
    @staticmethod
    def isa(other: Any) -> Any: ...
    def sibling(self, other: Any) -> Any: ...
    def eq(self, other: Any) -> Any: ...
    @classmethod
    def infer(cls: Any, name: Any, value: Any) -> Any: ...
    @property
    def raw_value(self) -> None: ...
    @property
    def type_name(self) -> None: ...
    def __hash__(self) -> Any: ...
    def __eq__(self, other: Any) -> Any: ...

AttrClass: Any

def xget(obj: Any, idx: Any) -> Any: ...

class AttrQuery(tuple):
    def __new__(cls: Any, parts: Any, *params: Any, **opts: Any) -> Any: ...
    @staticmethod
    def from_text(text: Any) -> Any: ...

def idig(obj: Any, path: Any) -> Any: ...
def dig(obj: Any, path: Any) -> Any: ...
