from typing import Any, Iterable, List, TypeVar

T = TypeVar('T')

class Box:
    inner: T
    @property
    def unboxed(self) -> T: ...
    def __init__(self, inner: Any) -> None: ...

def fromiter(objs: Iterable[Any]) -> List[type]: ...
def nick(x: Any) -> str: ...
