from typing import Any, Generator, Union

class GListlike:
    __gen__: Generator
    __cursor__: int
    __working__: bool
    __consumed__: Any = ...
    def __init__(self, gen: Any, *args: Any, **kwargs: Any) -> None: ...
    def takenext(self): ...
    def consume(self) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: Union[int, range]) -> Any: ...
