from typing import Any

def expose(x: Any, shrink_right: int=...) -> str: ...
def look(x: Any, shrink_right: int=...) -> None: ...
def guessdesc(value: Any) -> str: ...
def genabneuyaml(cursor: Any, ident: Any=..., name: Any=..., maxrecur: Any=..., spacing: Any=...) -> None: ...
def abneuyaml(cursor: Any, ident: Any=..., name: Any=..., maxrecur: Any=...) -> None: ...
