from typing import Any

def nice(ob: Any, compress: int=...) -> Any: ...
def binstr(value: Any, width: int=...) -> Any: ...
def nv(value: Any, width: int=...) -> Any: ...
def snv(value: Any, width: int=...) -> Any: ...
def visual_bits_print(value: Any, width: int=...) -> Any: ...
