from typing import Any

class FSM:
    state: Any = ...
    def __init__(self, initial: Any) -> None: ...
    def methods(self): ...
    def transition(self, state: Any, *args: Any, **kwargs: Any): ...

def state(name: Any): ...
def transits(desc: Any): ...
