from typing import Any

def nice(ob: Any, compress: int = ...): ...
def binstr(value: Any, width: int = ...): ...
def nv(value: Any, width: int = ...): ...
def snv(value: Any, width: int = ...): ...
def visual_bits_print(value: Any, width: int = ...): ...
